// Verifies every YouTube ID referenced in the curriculum via YouTube's public oEmbed endpoint
// (returns 200 only for public, existing, embeddable videos). Writes:
//   src/js/data/videos.js  - id -> { title, author } registry used by the app
//   docs/VIDEOS.md         - human-readable verification report
// Exits non-zero if any video fails, so it can gate releases.
import { writeFileSync } from 'node:fs';
import { DRILLS } from '../src/js/data/drills.js';
import { EXERCISES } from '../src/js/data/exercises.js';

const used = new Map(); // id -> [where]
const add = (id, where) => used.set(id, [...(used.get(id) || []), where]);
for (const d of DRILLS) d.videos.forEach((v) => add(v, `${d.disc}: ${d.name}`));
for (const ex of Object.values(EXERCISES)) for (const s of ex.stages) s.videos.forEach((v) => add(v, `${ex.name}: ${s.name}`));

async function check(id, tries = 3) {
  const url = `https://www.youtube.com/oembed?format=json&url=${encodeURIComponent('https://www.youtube.com/watch?v=' + id)}`;
  for (let i = 0; i < tries; i++) {
    try {
      const r = await fetch(url);
      if (r.ok) { const j = await r.json(); return { ok: true, title: j.title, author: j.author_name }; }
      if (r.status === 401 || r.status === 403 || r.status === 404 || r.status === 400) return { ok: false, status: r.status };
    } catch { /* retry */ }
    await new Promise((res) => setTimeout(res, 800 * (i + 1)));
  }
  return { ok: false, status: 'network' };
}

const registry = {};
const failed = [];
for (const id of used.keys()) {
  const r = await check(id);
  if (r.ok) registry[id] = { title: r.title, author: r.author };
  else failed.push([id, r.status]);
}

const today = new Date().toISOString().slice(0, 10);
writeFileSync(new URL('../src/js/data/videos.js', import.meta.url),
  `// GENERATED by scripts/verify-videos.mjs on ${today} - do not edit by hand.\n` +
  `// Every entry was confirmed public + embeddable via YouTube oEmbed.\n` +
  `export const VERIFIED_ON = '${today}';\nexport const VIDEOS = ${JSON.stringify(registry, null, 2)};\n`);

const rows = [...used.entries()].map(([id, where]) => {
  const v = registry[id];
  return `| ${v ? 'OK' : 'FAIL'} | [${(v?.title || id).replace(/\|/g, '/')}](https://www.youtube.com/watch?v=${id}) | ${v?.author || '-'} | ${where.join('; ')} |`;
});
writeFileSync(new URL('../docs/VIDEOS.md', import.meta.url),
  `# Verified training videos\n\nChecked ${today} via YouTube oEmbed (public + embeddable). Re-run: \`npm run verify:videos\`.\n\n` +
  `${registry && Object.keys(registry).length} OK, ${failed.length} failed.\n\n| Status | Video | Channel | Used for |\n|---|---|---|---|\n${rows.join('\n')}\n`);

console.log(`verified ${Object.keys(registry).length}/${used.size}`);
if (failed.length) { console.error('FAILED:', failed); process.exit(1); }
